### ISSUE TITLE
Can't properly download the project

### ISSUE THREAD

**Issue by wildfat** [ProdiG66/UE_PID_Controller#1]
Hello @ProdiG66 
I was wondering to see an implementation of the algorithm you have done, but unfortunately I couldn't get it the right way.
GitDesktop reports the problem:
"Error downloading object: Content/Blueprints/Actors/BP_Cam.uasset (4f6f4ec): Smudge error: Error downloading Content/Blueprints/Actors/BP_Cam.uasset (4f6f4ecc77936962881742024155c73adb0fa6512e0f1dafc605f43675d44d4b): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access."
It seems like you have reached your LFS limit.

**Comment by ProdiG66** [comment]
Added additional LFS Data to increase limit. Marking as resolved

**Comment by ProdiG66** [comment]
Added additional LFS Data to increase limit. Marking as resolved
